//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using Tender.Domain;


namespace Tender.Repository.Models.Mapping
{
    public partial class TenderUserMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TenderUser>
    {
        public TenderUserMap()
        {
            // table
            ToTable("TenderUser", "dbo");

            // keys
            HasKey<Guid>(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.Company)
                .HasColumnName("Company")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.ContactPerson)
                .HasColumnName("ContactPerson")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.ContactNum)
                .HasColumnName("ContactNum")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.BusinessLicense)
                .HasColumnName("BusinessLicense")
                .HasMaxLength(500)
                .IsRequired();
            Property(t => t.CashDeposit)
                .HasColumnName("CashDeposit")
                .IsRequired()
                ;
            //Property(t => t.BizCode)
            //    .HasColumnName("BizCode")
            //    .HasMaxLength(255)
            //    .IsRequired();
            //Property(t => t.CreateTime)
            //    .HasColumnName("CreateTime")
            //    .IsRequired();
            //Property(t => t.CrateId)
            //    .HasColumnName("CrateId")
            //    .IsOptional();

            // Relationships
        }
    }
}
