//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using Tender.Domain;        

namespace Tender.Repository.Models.Mapping
{
    public partial class TenderInfoMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TenderInfo>
    {
        public TenderInfoMap()
        {
            // table
            ToTable("TenderInfo", "dbo");

            // keys

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.Description)
                .HasColumnName("Description")
                .HasMaxLength(16)
                .IsRequired();
            Property(t => t.StartTime)
                .HasColumnName("StartTime")
                .IsRequired();
            Property(t => t.EndTime)
                .HasColumnName("EndTime")
                .IsRequired();
            Property(t => t.Cycle)
                .HasColumnName("Cycle")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.State)
                .HasColumnName("State")
                .IsRequired();
            Property(t => t.FirstUser)
                .HasColumnName("FirstUser")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.SecondUser)
                .HasColumnName("SecondUser")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.CreateDate)
                .HasColumnName("CreateDate")
                .IsRequired();

            // Relationships
        }
    }
}
