//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Tender.Repository.Models.Mapping
{
    public partial class TenderUserMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Tender.Domain.TenderUser>
    {
        public TenderUserMap()
        {
            // table
            ToTable("TenderUser", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.Company)
                .HasColumnName("Company")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.ContactPerson)
                .HasColumnName("ContactPerson")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.ContactNum)
                .HasColumnName("ContactNum")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.BusinessLicense)
                .HasColumnName("BusinessLicense")
                .HasMaxLength(500)
                .IsRequired();
            Property(t => t.CashDeposit)
                .HasColumnName("CashDeposit")
                .HasPrecision(18, 2)
                .IsRequired();

            // Relationships
        }
    }
}
