//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Tender.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class LogDetails 
    {
        public LogDetails()
        {
            this.LogID = 0;
            this.LogDate = DateTime.Now;
            this.LogThread = string.Empty;
            this.LogLevel = string.Empty;
            this.LogLogger = string.Empty;
            this.LogMessage = string.Empty;
            this.LogActionClick = string.Empty;
            this.UserName = string.Empty;
            this.UserIP = string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int LogID { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime LogDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LogThread { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LogLevel { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LogLogger { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LogMessage { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string LogActionClick { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UserName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string UserIP { get; set; }

    }
}