//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Tender.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class TenderUser
    {
        public TenderUser()
        {
          this.Name= string.Empty;
          this.Company= string.Empty;
          this.ContactPerson= string.Empty;
          this.ContactNum= string.Empty;
          this.BusinessLicense= string.Empty;
          this.CashDeposit= 0;
        }

        /// <summary>
	    /// 主键id，关联user表id
	    /// </summary>
        public System.Guid Id { get; set; }
        /// <summary>
	    /// 名称
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 公司名称，发票抬头
	    /// </summary>
        public string Company { get; set; }
        /// <summary>
	    /// 联系人
	    /// </summary>
        public string ContactPerson { get; set; }
        /// <summary>
	    /// 联系方式
	    /// </summary>
        public string ContactNum { get; set; }
        /// <summary>
	    /// 营业执照
	    /// </summary>
        public string BusinessLicense { get; set; }
        /// <summary>
	    /// 保证金
	    /// </summary>
        public decimal CashDeposit { get; set; }

    }
}